### ISSUE TITLE
Warnings on running the convert.py script

### ISSUE THREAD

**Issue by Arora0** [Arora0/nomad-parser-nexus#12]
The following warnings remain when the convert.py script is run:

Attributes were not found for element /@default.
The path, /@default, is being written but has no documentation.
The path, /ENTRY[entry]/DATA[data]/data/@units, is being written but has no documentation.

**Comment by rettigl** [comment]
The @default is documented in NXroot, which is currently not checked. Need to be added to the checking algorithm. Ignore for now
The Data/@units has been added to a new version of NXmpes, but the yaml2nxdl is broken at the moment. I will push once this is resolved.

**Comment by rettigl** [comment]
The data/@units field is there in the current mpes application definition. The other issue needs to be fixed in the converter code.
