### ISSUE TITLE
Re-examining fields in NXDistortion

### ISSUE THREAD

**Issue by Arora0** [Arora0/nomad-parser-nexus#2]
- [x] Suggestion:The field, 'field', that currently takes in two 2-d arrays to handle separately, the rdeform_field and cdeform_field.
- [x] The fields 'original points_x' and 'original points_y' to merged into a single field, 'original points' ?

**Comment by rettigl** [comment]
I generated a new version of NXdistortion in the gitlab repository, please update the config file correspondingly.

**Comment by Arora0** [comment]
Done. The converter doesn't break (in my newly cloned forked repo) if the new base classes aren't present in the definitions folder. For ex: even if there is no NXDistortion in the definitions folder, it works smoothly. Something that I don't understand.

**Comment by rettigl** [comment]
Do you maybe use the same venv? chec what the location of your installed parser-nexus installation is. The definitions are pulled relative to this installation, not from where you call the convert.py (it includes the parser-nexus package, and that is pulled from a different place potentially).

**Comment by Arora0** [comment]
Sorry, missed this. 
I see. Yes, I am using the same venv wherein I have the nexusparser installed. It is also using the main repository's helper.py etc. Is it then needed to have a new venv?

**Comment by rettigl** [comment]
Either that or you re-install the nexusparser package or your new branch/checkout in the venv with pip install -e . [all]
